# Generated by Django 5.2 on 2025-04-07 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('time_format_12h', models.BooleanField(default=False)),
                ('timezone', models.CharField(choices=[('Asia/Beirut', 'Asia/Beirut'), ('Asia/Bishkek', 'Asia/Bishkek'), ('Asia/Brunei', 'Asia/Brunei'), ('Asia/Kolkata', 'Asia/Kolkata')], default='Asia/Kolkata', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('space_type', models.CharField(choices=[('Room', 'Room'), ('Hall', 'Hall'), ('Office', 'Office')], default='Room', max_length=100)),
                ('num_of_floor', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building', to='keystone.building')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('floor', models.IntegerField()),
                ('disable_adhoc_booking', models.BooleanField(default=False)),
                ('meeting_confirmation', models.BooleanField(default=False)),
                ('shoe_meeting_title', models.BooleanField(default=False)),
                ('show_meeting_organizer', models.BooleanField(default=False)),
                ('enable_scheduling', models.BooleanField(default=False)),
                ('pin_required', models.BooleanField(default=False)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='keystone.building')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='keystone.space')),
            ],
        ),
    ]
